version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gaia-postgres
    environment:
      POSTGRES_USER: gaia
      POSTGRES_PASSWORD: gaia_dev_password
      POSTGRES_DB: gaia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gaia-network

  redis:
    image: redis:7-alpine
    container_name: gaia-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gaia-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gaia-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - ./templates:/app/templates
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://gaia:gaia_dev_password@postgres:5432/gaia_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - postgres
      - redis
    networks:
      - gaia-network

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gaia-celery-worker
    command: celery -A app.tasks.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
      - ./templates:/app/templates
    environment:
      - DATABASE_URL=postgresql://gaia:gaia_dev_password@postgres:5432/gaia_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - postgres
      - redis
    networks:
      - gaia-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gaia-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - gaia-network

volumes:
  postgres_data:
  redis_data:

networks:
  gaia-network:
    driver: bridge
